//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandBox.WebUi.Pages.Information {
    
    
    public partial class СonsolidatedReport {
        
        /// <summary>
        /// LUsageOfDifferentTypesOfLIR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxLabel LUsageOfDifferentTypesOfLIR;
        
        /// <summary>
        /// WCCUsageOfDifferentTypesOfLIR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.XtraCharts.Web.WebChartControl WCCUsageOfDifferentTypesOfLIR;
        
        /// <summary>
        /// ASPxLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel1;
        
        /// <summary>
        /// WCCUsageOSForResearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.XtraCharts.Web.WebChartControl WCCUsageOSForResearch;
        
        /// <summary>
        /// LStatisticsHarmfulInterference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxLabel LStatisticsHarmfulInterference;
        
        /// <summary>
        /// WCCUsageOSForResearch0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.XtraCharts.Web.WebChartControl WCCUsageOSForResearch0;
    }
}
